Vagrant.configure("2") do |config|  
  config.vm.define "jenkins-master" do |master|
    master.vm.box = "generic/ubuntu2204" 
    master.vm.network "private_network", ip: "192.168.56.11"
    master.vm.hostname = "jenkins-master"
    master.vm.provider "virtualbox" do |virtualbox|
      virtualbox.memory = "2048"
      virtualbox.cpus = "2"
    end
    master.vm.provision "shell", path: "master.sh"
  end 
  config.vm.define "jenkins-agent" do |agent|
    agent.vm.box = "generic/ubuntu2204"
    agent.vm.network "private_network", ip: "192.168.56.12"
    agent.vm.hostname = "jenkins-agent"
    agent.vm.provider "virtualbox" do |virtualbox|
      virtualbox.memory = "2048"
      virtualbox.cpus = "2"
    end
    agent.vm.provision "shell", path: "agent.sh"
  end
  config.vm.boot_timeout = 1000
end

