Vagrant.configure("2") do |config|  
  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/focal64" 
    db.vm.network "private_network", ip: "192.168.56.12"
    db.vm.hostname = "db-vm"
    db.vm.provision "shell", path: "db.sh"
    db.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "2"
    end
  end 
  config.vm.define "app" do |app|
    app.vm.box = "ubuntu/focal64"
    app.vm.network "private_network", ip: "192.168.56.11"
    app.vm.hostname = "app-vm"
    app.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "2"
    end
    app.vm.provision "shell", path: "app.sh"
  end
  config.vm.boot_timeout = 1000
end