---
# handlers file for jenkins_worker
- name: update_cache_docker
  apt:
    update_cache: yes
  become: true
  tags: install_docker

- name: restart_docker
  service:
    name: docker
    state: reload
  become: true
  tags: install_docker