---
# tasks file for nginx
- name: Install docker and docker-compose
  become: true
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose
    state: present
    update_cache: yes
  tags: install_docker

- name: Ensure docker service is running
  become: true
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  tags: install_docker

- name: Add ubuntu user to docker group
  become: true
  ansible.builtin.user:
    name: ubuntu
    groups: docker
    append: true
  tags: docker_group

- name: Copy docker-compose.yml
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /home/ubuntu/docker-compose.yml
    owner: ubuntu
    group: ubuntu
    mode: '0644'
  become: true
  tags: copy

- name: Start docker-compose
  community.docker.docker_compose:
    project_src: /home/ubuntu/
    state: present
  become: true
  tags: start_compose
